In [1]:
import bs4
from bs4 import BeautifulSoup
import requests as rq
import re
import pandas as pd
import numpy as np
import datetime 
import os
import math
import pymongo

In [2]:
def convdollar(x):
    """
    Just a parsing function converting 2.5k to 2500, 1mil to 1000000
    """
    if 'k' in x:
        return float(x.replace('k',''))*1000
    else:
        return float(x)*1000000

In [3]:
millnames = ['',' Thousand',' Million',' Billion',' Trillion']

def millify(n):
    n = float(n)
    millidx = max(0,min(len(millnames)-1,
                        int(math.floor(0 if n == 0 else math.log10(abs(n))/3))))

    return '{:.0f}{}'.format(n / 10**(3 * millidx), millnames[millidx])

In [4]:
def scrape():
    """
    Gets all box office data from 2019 to present from boxofficemojo.com
    """
    years=[str(a) for a in range(2019,2020)]
    df_list=[]
    for year in years:
        r=rq.get('https://www.boxofficemojo.com/yearly/chart/?view2=worldwide&yr=%s&p=.htm' % year)
        print('Box Office data for %s scraped' % year)
        p=BeautifulSoup(r.text,'html.parser')
            ### Look for the table ### 
        b=p.find_all('table')
        
        ### Usually the fourth table object on page ### 
        tb=b[3].find_all('td')
         ## Each data field is found in a <td> element in the fourth table. Store all data in a list ## 
        data=[]
        for i in tb:
            if i.find('a')!=None:
                data.append(i.find('a').contents[0])
            elif i.find('font')!=None:
                 data.append(i.find('font').contents[0])
            elif i.find('b')!=None:
                data.append(i.find('b').contents[0])
                ### Still a <b> tag left for <font> tags ## 
        data=[a.contents[0] if type(a)!=bs4.element.NavigableString else a for a in data]
        
        ### Strip special characters ### 
        data=[re.sub('[^A-Za-z0-9-. ]+', '', a) for a in data]
        
        ### Fill NaNs ### 
        data=[np.nan if a =='na' else a for a in data]
        
        ### Define the feature names ###
        columns=['bo_year_rank','title','studio','worldwide-gross','domestic-gross','domestic-pct','overseas-gross','overseas-pct']
        
        ### First 6 elements are column headers # 
        to_df=data[6:]
        
        ### Escape clause in case the layout changes from year to year ### 
        if len(to_df)%len(columns) != 0:
            print('Possible table misalignment in table for year %s' % year)
            break
            
            ### Convert to pandas dataframe ### 
        
        nrow=int(len(to_df)/len(columns))
        df=pd.DataFrame(np.array(to_df).reshape(nrow,8),columns=columns)
        df[['worldwide-gross','domestic-gross','overseas-gross']]=df[['worldwide-gross','domestic-gross','overseas-gross']].applymap(lambda x:convdollar(x))
        df['bo_year']=int(year)
        df_list.append(df)

        main=pd.concat(df_list)
    
        # Store data into csv # 
        #main.to_csv(os.path.join("output","current_boxoffice_mojo.csv"))
        return (main)
        print (main)

In [5]:
if __name__ == "__main__": 

    dirtymovies_df=scrape()

Box Office data for 2019 scraped

In [6]:
 dirtymovies_df

,bo_year_rank,title,studio,worldwide-gross,domestic-gross,domestic-pct,overseas-gross,overseas-pct,bo_year
0,1,Avengers Endgame,BV,1.664200e+09,452400000.0,27.2,1.211800e+09,72.8,2019
1,2,Captain Marvel,BV,1.112800e+09,416000000.0,37.4,6.968000e+08,62.6,2019
2,3,The Wandering Earth,CMC,6.998000e+08,5900000.0,0.8,6.939000e+08,99.2,2019
3,4,How to Train Your Dragon The Hidden World,Uni.,5.164000e+08,159700000.0,30.9,3.567000e+08,69.1,2019
4,5,Alita Battle Angel,Fox,4.047000e+08,85700000.0,21.2,3.190000e+08,78.8,2019
5,6,Shazam,WB NL,3.472000e+08,132500000.0,38.2,2.147000e+08,61.8,2019
6,7,Dumbo 2019,BV,3.293000e+08,108100000.0,32.8,2.212000e+08,67.2,2019
7,8,Us,Uni.,2.499000e+08,173300000.0,69.3,7.660000e+07,30.7,2019
8,9,Glass,Uni.,2.470000e+08,111000000.0,45.0,1.359000e+08,55.0,2019
9,10,The LEGO Movie 2 The Second Part,WB,1.905000e+08,105700000.0,55.5,8.480000e+07,44.5,2019
10,11,Escape Room,Sony,1.551000e+08,57000000.0,36.7,9.810000e+07,63.3,2019
11,12,The Upside,STX,1.221000e+08,108200000.0,88.6,1.390000e+07,11.4,2019
12,13,Extreme Job,CJ,1.199000e+08,1600000.0,1.3,1.184000e+08,98.7,2019
13,14,Dragon Ball Super Broly,FUN,1.108000e+08,30700000.0,27.7,8.010000e+07,72.3,2019
14,15,Wonder Park,Par.,1.048000e+08,45100000.0,43.0,5.970000e+07,57.0,2019
15,16,Pet Sematary 2019,Par.,1.033000e+08,53100000.0,51.4,5.020000e+07,48.6,2019
16,17,The Curse of La Llorona,WB NL,8.960000e+07,44100000.0,49.2,4.550000e+07,50.8,2019
17,18,A Dogs Way Home,Sony,7.590000e+07,42000000.0,55.4,3.390000e+07,44.6,2019
18,19,Tyler Perrys A Madea Family Funeral,LGF,7.460000e+07,73100000.0,98.0,1.500000e+06,2.0,2019
19,20,Five Feet Apart,LGF,7.440000e+07,45400000.0,61.1,2.890000e+07,38.9,2019
20,21,What Men Want,Par.,7.220000e+07,54600000.0,75.6,1.760000e+07,24.4,2019
21,22,Happy Death Day 2U,Uni.,6.420000e+07,28100000.0,43.7,3.620000e+07,56.3,2019
22,23,Cold Pursuit,LGS,5.920000e+07,32100000.0,54.3,2.710000e+07,45.7,2019
23,24,After 2019,Aviron,5.570000e+07,11800000.0,21.2,4.390000e+07,78.8,2019
24,25,Little,Uni.,4.350000e+07,36900000.0,84.8,6.600000e+06,15.2,2019
25,26,Fighting with My Family,MGM,3.850000e+07,22900000.0,59.5,1.560000e+07,40.5,2019
26,27,Breakthrough,Fox,3.660000e+07,28800000.0,78.6,7.800000e+06,21.4,2019
27,28,The Kid Who Would be King,Fox,3.200000e+07,16800000.0,52.5,1.520000e+07,47.5,2019
28,29,Mia and the White Lion,Ledafilms,2.680000e+07,392000.0,1.5,2.640000e+07,98.5,2019
29,30,Total Dhamaal,FIP,2.500000e+07,2200000.0,8.7,2.290000e+07,91.3,2019
...,...,...,...,...,...,...,...,...,...
58,59,The Man Who Killed Don Quixote,Fathom,3.280000e+05,328000.0,100.0,NaN,0.0,2019
59,60,P Storm,CMC,3.090000e+05,309000.0,100.0,NaN,0.0,2019
60,61,Junglee,VPD,2.960000e+05,296000.0,100.0,NaN,0.0,2019
61,62,I Want to Eat Your Pancreas,Fathom,2.770000e+05,277000.0,100.0,NaN,0.0,2019
62,63,Mobile Suit Gundam NT Narrative,Fathom,2.590000e+05,259000.0,100.0,NaN,0.0,2019
63,64,Red Joan,IFC,2.470000e+05,247000.0,100.0,NaN,0.0,2019
64,65,Romeo Akbar Walter,Eros,2.360000e+05,236000.0,100.0,NaN,0.0,2019
65,66,Master Z Ip Man Legacy,WGUSA,1.890000e+05,189000.0,100.0,NaN,0.0,2019
66,67,Monty Pythons Life of Brian 40th Anniversary,Trafalgar,1.580000e+05,158000.0,100.0,NaN,0.0,2019
67,68,Peterloo,Amazon,1.460000e+05,146000.0,100.0,NaN,0.0,2019
68,69,Okkos Inn,GK,1.250000e+05,125000.0,100.0,NaN,0.0,2019
69,70,Sunset 2019,SPC,1.190000e+05,119000.0,100.0,NaN,0.0,2019
70,71,Ruben Brandt Collector,SPC,1.150000e+05,115000.0,100.0,NaN,0.0,2019
71,72,Belle and Sebastian Friends for Life,EOne,1.060000e+05,106000.0,100.0,NaN,0.0,2019
72,73,The Image Book,KL,9.420000e+04,94200.0,100.0,NaN,0.0,2019
73,74,The Crossing,CMC,9.090000e+04,90900.0,100.0,NaN,0.0,2019
74,75,Sonchiriya,PackYourBag,8.680000e+04,86800.0,100.0,NaN,0.0,2019
75,76,The Heiresses,Distrib.,7.250000e+04,72500.0,100.0,NaN,0.0,2019
76,77,Storm Boy,Good Deed,7.180000e+04,71800.0,100.0,NaN,0.0,2019
77,78,Styx,FM,6.790000e+04,67900.0,100.0,NaN,0.0,2019
78,79,3 Faces,KL,6.620000e+04,66200.0,100.0,NaN,0.0,2019
79,80,Ramen Shop,Strand,5.430000e+04,54300.0,100.0,NaN,0.0,2019
80,81,He Matado a mi Marido,Ham,3.520000e+04,31400.0,89.3,3.800000e+03,10.7,2019
81,82,The Sower,FM,3.410000e+04,34100.0,100.0,NaN,0.0,2019
82,83,The Wild Pear Tree,CGld,3.160000e+04,31600.0,100.0,NaN,0.0,2019
83,84,The Hole in the Ground,A24,2.110000e+04,21100.0,100.0,NaN,0.0,2019
84,85,Touch Me Not,KL,1.380000e+04,13800.0,100.0,NaN,0.0,2019
85,86,Ferrante Fever,Greenwich,1.110000e+04,11100.0,100.0,NaN,0.0,2019
86,87,Patrick,INDEP,6.300000e+03,6300.0,100.0,NaN,0.0,2019
87,88,Tall Tales from the Magical Garden of Antoon K...,VPD,2.000000e+02,200.0,100.0,NaN,0.0,2019

In [7]:
## Cleaning data by dropping the unessery rows (10-87) drops the bottom 78 trows
dirtymovies_df[:-78]

,bo_year_rank,title,studio,worldwide-gross,domestic-gross,domestic-pct,overseas-gross,overseas-pct,bo_year
0,1,Avengers Endgame,BV,1.664200e+09,452400000.0,27.2,1.211800e+09,72.8,2019
1,2,Captain Marvel,BV,1.112800e+09,416000000.0,37.4,6.968000e+08,62.6,2019
2,3,The Wandering Earth,CMC,6.998000e+08,5900000.0,0.8,6.939000e+08,99.2,2019
3,4,How to Train Your Dragon The Hidden World,Uni.,5.164000e+08,159700000.0,30.9,3.567000e+08,69.1,2019
4,5,Alita Battle Angel,Fox,4.047000e+08,85700000.0,21.2,3.190000e+08,78.8,2019
5,6,Shazam,WB NL,3.472000e+08,132500000.0,38.2,2.147000e+08,61.8,2019
6,7,Dumbo 2019,BV,3.293000e+08,108100000.0,32.8,2.212000e+08,67.2,2019
7,8,Us,Uni.,2.499000e+08,173300000.0,69.3,7.660000e+07,30.7,2019
8,9,Glass,Uni.,2.470000e+08,111000000.0,45.0,1.359000e+08,55.0,2019
9,10,The LEGO Movie 2 The Second Part,WB,1.905000e+08,105700000.0,55.5,8.480000e+07,44.5,2019

In [8]:
#create new dataframe for top 10 
toptenmovies_df = dirtymovies_df[:-78]

In [9]:
toptenmovies_df

,bo_year_rank,title,studio,worldwide-gross,domestic-gross,domestic-pct,overseas-gross,overseas-pct,bo_year
0,1,Avengers Endgame,BV,1.664200e+09,452400000.0,27.2,1.211800e+09,72.8,2019
1,2,Captain Marvel,BV,1.112800e+09,416000000.0,37.4,6.968000e+08,62.6,2019
2,3,The Wandering Earth,CMC,6.998000e+08,5900000.0,0.8,6.939000e+08,99.2,2019
3,4,How to Train Your Dragon The Hidden World,Uni.,5.164000e+08,159700000.0,30.9,3.567000e+08,69.1,2019
4,5,Alita Battle Angel,Fox,4.047000e+08,85700000.0,21.2,3.190000e+08,78.8,2019
5,6,Shazam,WB NL,3.472000e+08,132500000.0,38.2,2.147000e+08,61.8,2019
6,7,Dumbo 2019,BV,3.293000e+08,108100000.0,32.8,2.212000e+08,67.2,2019
7,8,Us,Uni.,2.499000e+08,173300000.0,69.3,7.660000e+07,30.7,2019
8,9,Glass,Uni.,2.470000e+08,111000000.0,45.0,1.359000e+08,55.0,2019
9,10,The LEGO Movie 2 The Second Part,WB,1.905000e+08,105700000.0,55.5,8.480000e+07,44.5,2019

In [10]:
##clean new dataframe for top 10 by removing rows domestic-pct, overseas-pct
toptenmovies_df.drop("domestic-pct", axis=1).drop("overseas-pct", axis=1)

,bo_year_rank,title,studio,worldwide-gross,domestic-gross,overseas-gross,bo_year
0,1,Avengers Endgame,BV,1.664200e+09,452400000.0,1.211800e+09,2019
1,2,Captain Marvel,BV,1.112800e+09,416000000.0,6.968000e+08,2019
2,3,The Wandering Earth,CMC,6.998000e+08,5900000.0,6.939000e+08,2019
3,4,How to Train Your Dragon The Hidden World,Uni.,5.164000e+08,159700000.0,3.567000e+08,2019
4,5,Alita Battle Angel,Fox,4.047000e+08,85700000.0,3.190000e+08,2019
5,6,Shazam,WB NL,3.472000e+08,132500000.0,2.147000e+08,2019
6,7,Dumbo 2019,BV,3.293000e+08,108100000.0,2.212000e+08,2019
7,8,Us,Uni.,2.499000e+08,173300000.0,7.660000e+07,2019
8,9,Glass,Uni.,2.470000e+08,111000000.0,1.359000e+08,2019
9,10,The LEGO Movie 2 The Second Part,WB,1.905000e+08,105700000.0,8.480000e+07,2019

In [11]:
Cleanedtoptenmovies_df= toptenmovies_df.drop("domestic-pct", axis=1).drop("overseas-pct", axis=1)

In [12]:
Cleanedtoptenmovies_df

,bo_year_rank,title,studio,worldwide-gross,domestic-gross,overseas-gross,bo_year
0,1,Avengers Endgame,BV,1.664200e+09,452400000.0,1.211800e+09,2019
1,2,Captain Marvel,BV,1.112800e+09,416000000.0,6.968000e+08,2019
2,3,The Wandering Earth,CMC,6.998000e+08,5900000.0,6.939000e+08,2019
3,4,How to Train Your Dragon The Hidden World,Uni.,5.164000e+08,159700000.0,3.567000e+08,2019
4,5,Alita Battle Angel,Fox,4.047000e+08,85700000.0,3.190000e+08,2019
5,6,Shazam,WB NL,3.472000e+08,132500000.0,2.147000e+08,2019
6,7,Dumbo 2019,BV,3.293000e+08,108100000.0,2.212000e+08,2019
7,8,Us,Uni.,2.499000e+08,173300000.0,7.660000e+07,2019
8,9,Glass,Uni.,2.470000e+08,111000000.0,1.359000e+08,2019
9,10,The LEGO Movie 2 The Second Part,WB,1.905000e+08,105700000.0,8.480000e+07,2019

  if x is >= 1000000000 then convert to "1.xx billion"  to make more readable we are going from float to string 
  else convert to xxxmillion 
  
  Next steps for arjun figure out function above then put finished dataframe into mongodbcollection

In [13]:
# Connect to mongo
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# Connect to Top 10 database
db = client.top_10_db

# If collection books exists, drop it so the new top 10 information will replace it
db.movies.drop()

#Create new empty books collection
movies = db.movies

# Insert top 10 books/movies/music into database
data = Cleanedtoptenmovies_df.to_dict(orient='records')
db.movies.insert_many(data)